#ifndef WII_MENU_SETTINGS_SCENE_H
#define WII_MENU_SETTINGS_SCENE_H

#include "wii_menu/font_cache.h"
#include "wii_menu/platform.h"
#include "wii_menu/texture_cache.h"

#include <stdbool.h>

typedef struct WmSettingsScene WmSettingsScene;

typedef enum WmSettingsPhase {
    WM_SETTINGS_CLOSED,
    WM_SETTINGS_APPEAR,
    WM_SETTINGS_READY,
    WM_SETTINGS_SCROLL
} WmSettingsPhase;

typedef enum WmSettingsControl {
    WM_SETTINGS_CONTROL_NONE,
    WM_SETTINGS_CONTROL_BACK,
    WM_SETTINGS_CONTROL_PREVIOUS,
    WM_SETTINGS_CONTROL_NEXT,
    WM_SETTINGS_CONTROL_ITEM_1,
    WM_SETTINGS_CONTROL_ITEM_2,
    WM_SETTINGS_CONTROL_ITEM_3,
    WM_SETTINGS_CONTROL_ITEM_4,
    WM_SETTINGS_CONTROL_ITEM_5,
    WM_SETTINGS_CONTROL_ITEM_6
} WmSettingsControl;

typedef struct WmSettingsSnapshot {
    unsigned page; /* One through three, as labeled by the source pages. */
    unsigned category; /* Zero on the index; otherwise the selected category. */
    unsigned detail; /* Zero on a category page; otherwise its selected screen. */
    unsigned selection; /* Staged zero-based choice on selectable screens. */
    unsigned year;
    unsigned month;
    unsigned day;
    unsigned hour;
    unsigned minute;
    unsigned sensitivity; /* One through five. */
    char nickname[11]; /* Local in-memory edit, up to ten ASCII characters. */
    bool parental_enabled;
    bool connect24_enabled;
    bool standby_enabled;
    unsigned slot_light;
    bool internet_agreement;
    unsigned connection_slot; /* One through three on Internet profile pages. */
    unsigned country_page;
    unsigned country_choice;
    bool local_format_complete;
    WmSettingsPhase phase;
    float phase_frame;
    WmSettingsControl hover;
    float hover_opacity; /* Source image rollover is immediate: zero or one. */
    float page_opacity; /* Current page in a category/detail raster crossfade. */
} WmSettingsSnapshot;

typedef struct WmSettingsProjection {
    float document_x;
    float document_width;
    float side_width;
} WmSettingsProjection;

/* The source System Menu's 608 x 456 Settings raster is generated by Opera
 * HTML. This first-party scene renders its three index pages and US category
 * entry screens. Its index page-change curve comes from the exported
 * SceenChange_b WAD layout. Console services are represented by local state. */
WmSettingsScene *wm_settings_scene_create(WmPlatform *platform,
                                           const char *assets_directory,
                                           WmTextureCache *textures,
                                           WmFontCache *fonts);
void wm_settings_scene_destroy(WmSettingsScene *scene);
/* The source 16:9 surface has a 608-pixel document between two 112-pixel
 * side panels. Its 832-pixel raster is fitted into the 640-pixel framebuffer.
 * Leave disabled for the source 4:3 document and its original hit geometry. */
void wm_settings_scene_set_wide(WmSettingsScene *scene, bool wide);
WmSettingsProjection wm_settings_scene_projection(
    const WmSettingsScene *scene);
bool wm_settings_scene_open(WmSettingsScene *scene);
/* Open the Internet category directly from the Message Board's connection
 * prompt. Back from its category index exits instead of showing page two. */
bool wm_settings_scene_open_internet(WmSettingsScene *scene);
/* Discard transient navigation and input when HOME restarts the menu. */
void wm_settings_scene_reset(WmSettingsScene *scene);
void wm_settings_scene_advance(WmSettingsScene *scene, float frames);
WmSettingsSnapshot wm_settings_scene_snapshot(const WmSettingsScene *scene);
bool wm_settings_scene_update_question(const WmSettingsScene *scene);
bool wm_settings_scene_back(WmSettingsScene *scene);
bool wm_settings_scene_take_exit(WmSettingsScene *scene);
/* Reserved for a category unavailable in another resource variant. The
 * current US category screens all return zero through this function. */
unsigned wm_settings_scene_take_category(WmSettingsScene *scene);
const char *wm_settings_category_label(unsigned category);

/* Source HTML index hit geometry, projected from 608 pixels into the centered
 * 640-pixel logical framebuffer. This pure function is also used for tests. */
WmSettingsControl wm_settings_index_hit(unsigned page, int x, int y);
WmSettingsControl wm_settings_scene_hit(const WmSettingsScene *scene,
                                        int x, int y);
bool wm_settings_scene_hover(WmSettingsScene *scene,
                             WmSettingsControl control);
bool wm_settings_scene_activate(WmSettingsScene *scene,
                                WmSettingsControl control);
/* Date/Time arrows act on press and repeat after 400 ms, then every 150 ms.
 * A true result means the caller must suppress its ordinary release click. */
bool wm_settings_scene_pointer_down(WmSettingsScene *scene,
                                    WmSettingsControl control);
void wm_settings_scene_pointer_up(WmSettingsScene *scene);
/* The source Nickname input accepts ten characters. Until a native Wii
 * keyboard is ported, this adapter accepts printable ASCII keyboard input. */
bool wm_settings_scene_type_ascii(WmSettingsScene *scene, char character);
bool wm_settings_scene_backspace(WmSettingsScene *scene);
bool wm_settings_scene_editing_nickname(const WmSettingsScene *scene);

/* Draw inside a caller-owned platform frame, beneath its pointer. */
bool wm_settings_scene_draw(WmSettingsScene *scene);

#endif
