cc_add_platform(wii-menu "${WM_BACKEND}")
if(WM_BACKEND STREQUAL "metal")
    target_sources(wii-menu PRIVATE platform/apple/audio_platform_apple.c)
    target_link_libraries(wii-menu PRIVATE "-framework AudioToolbox")
elseif(WM_BACKEND STREQUAL "gles2")
    target_sources(wii-menu PRIVATE platform/linux/audio_platform_linux.c)
    target_link_libraries(wii-menu PRIVATE dl)
endif()
